### ISSUE TITLE
Post please a jar file for version 4.1

### ISSUE THREAD

**Issue by Rafinol** [airbus-cyber/graylog-plugin-correlation-count#23]
Hi, dear.
We cant build project. 
Can you send jar file for graylog version 4.1
Thank you

**Comment by frantz45** [comment]
Hello.
We meet some troubles to publish jar files in Github.
We will fix this soon, but at the moment you can download the jar files from maven : https://search.maven.org/artifact/com.airbus-cyber-security.graylog/graylog-plugin-correlation-count.
The v4.0.0 should works with Graylog v4.1.

**Comment by c8y3** [comment]
The publication of the jar files in the github Releases page is now back. (see https://github.com/airbus-cyber/graylog-plugin-correlation-count/releases)
Sorry for the inconvenience.
