### ISSUE TITLE
Upgrade to 4.2.x

### ISSUE THREAD

**Issue by koff75** [airbus-cyber/graylog-plugin-correlation-count#24]
Hi,

Could it be possible to upgrade the plugin to fix the compatibility to Graylog 4.2.x ?
I tried to compile the code on my computer using mvn package and get :
```
[INFO] [webpack-cli] Failed to load '/graylog-plugin-aggregation-count/webpack.config.js' config
[INFO] [webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

**Comment by dcantos1** [comment]
I also need the upgrade of the correlation and aggregator please. for version 4.2.X

**Comment by c8y3** [comment]
Hello,
The latest version (4.1.0) of the plugin (https://github.com/airbus-cyber/graylog-plugin-correlation-count/releases/tag/4.1.0) should be compatible with graylog >= 4.2.3.
Similarly, the latest version of the aggregation plugin (https://github.com/airbus-cyber/graylog-plugin-aggregation-count/releases/tag/4.1.0) should be compatible with graylog >= 4.2.3.
Hope this works for you.

**Comment by koff75** [comment]
Perfect ! Many thanks 💯
