### ISSUE TITLE
Escape special caracters in query

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-correlation-count#27]
Actual query doesn't work with some special caracters as "space".
I think some other caracters like ': \ "' should be escaped too.

https://github.com/airbus-cyber/graylog-plugin-correlation-count/blob/fbeae82ab3a7279a2850608b367cd3e657927b9e/src/main/java/com/airbus_cyber_security/graylog/events/processor/correlation/checks/CorrelationCount.java#L104

**Comment by c8y3** [comment]
If I understood well, it is the value that should be escaped.

**Comment by frantz45** [comment]
Yes it's the value.
Maybe we could add double quotes surrounding the value to not have to escape some values (it's what we do for logging_alert.messages_url).
Moreover according to Graylog documentation (https://docs.graylog.org/docs/query-language)
- The following value must be escaped: & | : \ / + - ! ( ) { } [ ] ^ " ~ * ? (it doesn't mention "space" but it needs to be escaped)
- There is no space between the colon and the value, so it isn't "name: value" but "name:value"

**Comment by c8y3** [comment]
The problem is now at line 171 of CorrelationCountProcessor: https://github.com/airbus-cyber/graylog-plugin-correlation-count/blob/7cae8e22027df661305a968d7fd273a68677a73c/src/main/java/com/airbus_cyber_security/graylog/events/processor/correlation/CorrelationCountProcessor.java#L171

**Comment by c8y3** [comment]
We could emulate either: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java#L190 or https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java#L118
In both case the value is surrounded by quotes. In addition, for the AggregationEventProcessor, the value is escaped. But not for the FieldContentValueAlertCondition. Maybe it is not needed in this case? Or it may be a bug in graylog?

**Comment by frantz45** [comment]
I don't have time to test but I reviewed the code and it's well escaped, it should work fine:
            String value = MoreSearch.luceneEscape(groupBy.getValue());
            builder.append(" AND ").append(name).append(": \"").append(value).append("\"");
