### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by soulmaster43** [airbus-cyber/graylog-plugin-correlation-count#6]
Hi,

I tested this plugin for Graylog version 3.1.2-1 and it is not working (as if I wasn't even installed)
Checked the logs but no errors were noticed.
![Capture](https://user-images.githubusercontent.com/19363009/65526412-5ec58b80-def1-11e9-85d4-ce6d7457f717.PNG)
![Capture2](https://user-images.githubusercontent.com/19363009/65526413-5f5e2200-def1-11e9-9ae5-ed1860fd9723.PNG)

**Comment by tomasnk** [comment]
Hi,

The plugin Correlation Count 1.2.X work only with Graylog 3.0.X

**Comment by soulmaster43** [comment]
Hi Thomas,

Thank you for your reply.

Could you tell me if this plugin will ever be updated for graylog 3.1?

Thank you

**Comment by tomasnk** [comment]
Hi,
The plugin will be updated, I hope for the end of this year.

**Comment by markdollan243** [comment]
Hi @tomasnk,

Are you planning to release a new version of this plugin finally? It is a very good plugin but it is a shame that cannot be installed on the latest version of Graylog. I know that the latest version of Graylog includes a correlation service but you have to pay the enterprise license to get this functionality.

Thanks.

**Comment by tomasnk** [comment]
Hi,
Graylog reworked completely the alert condition. We tried to update with the new way, but for the moment the condition is not triggered. I don't know if or when we will be able to make it fully work.

**Comment by markdollan243** [comment]
Ok, thank you anyway!

**Comment by tomasnk** [comment]
Please see Release 2.0.0 compatible with Graylog 3.2
